
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - script: |
      set -e
      dotnet restore
      dotnet build --configuration Release --no-restore
    workingDirectory: 'backend/.Net app'
    displayName: 'Restore and Build .NET Backend'

  - task: NodeTool@0
    displayName: 'Install Node.js 20'
    inputs:
      versionSpec: '20.x'


  - script: |
      set -e
      npm install
      npm run build
    workingDirectory: 'frontend/React App'
    displayName: 'Install and Build React Frontend'


  - task: PublishPipelineArtifact@1
    displayName: 'Publish React Build Artifact'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/frontend/React App/build'
      artifact: 'react-frontend'
      publishLocation: 'pipeline'

  - script: |
      set -e
      dotnet publish "backend/.Net app/TaskManager.Api.csproj" \
        --configuration Release \
        --output "$(Build.ArtifactStagingDirectory)/backend"
    displayName: 'Publish .NET Backend'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Backend Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/backend'
      artifact: 'dotnet-backend'
      publishLocation: 'pipeline'


